<MenuWidget>:
    id: mw
    opacity: 0
    canvas.before:
        Color:
            rgba: 0, 0, 0, .8
        Rectangle:
            size: self.size

    # Label:
        # font_name: 'fonts/DS-DIGI.TTF'
        # text: 'Hello'

    Button:
        id: yes_button
        text: root.parent.menu_button_one
        font_size: root.height/11
        font_name: 'fonts/DS-DIGI.TTF'
        color: 0,1,0 ,1
        size_hint: .18,.18
        pos_hint: {'center_x':.4, 'center_y':.3}
        on_press:root.parent.on_menu_button_one_press()

    Button:
        id: no_button
        text: root.parent.menu_button_two
        font_size: root.height/11
        font_name: 'fonts/DS-DIGI.TTF'
        color: 1,0,0 ,1
        size_hint: .18,.18
        pos_hint: {'center_x':.6, 'center_y':.3}
        on_press:root.parent.on_menu_button_two_press(),app.stop()

    Button:
        id: review
        text: 'Review'
        font_size: root.height/15
        font_name: 'fonts/DS-DIGI.TTF'
        size_hint: .18,.18
        # on_press: root.parent.on_menu_button_review()
        on_release: popup.open(), root.parent.popup_content()
        pos_hint: {'x':0, 'y':0}

    Popup:
        id: popup
        on_parent: if self.parent == mw: mw.remove_widget(self)
        title: 'Review'

        BoxLayout:
            orientation: 'vertical'
            Label:
                id: label
                # text: 'Default Text'
                text: root.parent.popup_label

            Button:
                text: 'Close'
                font_size: root.height/11
                font_name: 'fonts/DS-DIGI.TTF'
                size_hint: .18,.18
                on_release: popup.dismiss()